export const STORE_KEYS={intake:'sprint_lab_intake_v2',post:'sprint_lab_post_v2',baselines:'sprint_lab_baselines_v2',backupMeta:'sprint_lab_backup_meta_v1'};
export const dateOnly=(d=new Date())=>{const c=new Date(d.getTime()-d.getTimezoneOffset()*60000);return c.toISOString().slice(0,10)};
export const safeParse=(raw,fallback)=>{try{return raw?JSON.parse(raw):fallback}catch{return fallback}};
export const readStore=(k,f)=>safeParse(localStorage.getItem(k),f);
export const writeStore=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
export const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
export const toNum=(v)=>{const n=parseFloat(String(v).match(/-?\d+(\.\d+)?/)?.[0]??'');return Number.isFinite(n)?n:null};
export const fmtDate=(d)=>d?new Date(`${d}T00:00:00`).toLocaleDateString(): '—';
export const getWeekCount=(items)=>{const now=new Date();const weekAgo=new Date(now);weekAgo.setDate(now.getDate()-7);return items.filter(i=>new Date(i.date)>=weekAgo).length};
export const latest=(arr)=>arr?.length?arr[arr.length-1]:null;
